### ISSUE TITLE
COM3 doesnt show up in the tools ports tab

### ISSUE THREAD

**Issue by timmyboi57** [awolf78/KISS_OSD#44]
COM3 does not show up in the tools>ports tab I tried to upload using a different port: /dev/cu.Bluetooth-Incoming-Port. It says not in sync, I feel like I am missing something very obvious or I should just do this on a windows pc and save myself the headache but this is what I have at the moment.

**Comment by awolf78** [comment]
Sorry, not much of a MAC pro here. From what I heard it should work out of the box with a MAC (and not too ancient OSX).

**Comment by fedorcomander** [comment]
Port name you are trying to use says BLUETOOTH!

/dev/cu.Bluetooth-Incoming-Port

Pay attention. On mac works out of the box, or check CP2102 drivers from Sylabs.

https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers <https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers>

Also, there was some issue in previous mac osx, but fixed in high sierra. 

/FedorCommandrr
