### ISSUE TITLE
AIKON 4 in 1 current sensor is not working on micro minim OSD

### ISSUE THREAD

**Issue by Heidi87** [awolf78/KISS_OSD#49]
Hi,

I would like to know if the current sensor pin on the micro minim OSD is actually used within Kiss OSD 2.5.
My setup: AIKON 4 in1 ESC on Kiss v2 works great with the micro OSD, except of the current sensor.
Since the AIKON dose not support ESC current telemetry, I tried to connect the single current sensor to the micro OSD current pin, but it did not work. Can you please help me to solve the issue?
Thank you very much in advance!
Jan

**Comment by awolf78** [comment]
Sorry, but analog current sensor is not supported by KISS OSD. ESC telemetry is one of the core features for KISS, so my OSD relies and takes advantage of it as much as possible. Adding current sensor support is also not possible since I ran out of program space.
You are better off using MWOSD instead if you use a current sensor.

**Comment by Heidi87** [comment]
Ok I understand. I read about your new OSD with Impulsrc. Dose it support analog current sensor and will the size of it be similar to the micro minim osd? 

Thank you very much for the prompt answer it’s really helpful :) !!!

**Comment by awolf78** [comment]
The new OSD is on a PDB (called WolfPDB). So that won't be the greatest fit with a 4in1.

**Comment by Heidi87** [comment]
Ok sound’s like no option for me. But thank you for the support anyways!
